### ISSUE TITLE
undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE

### ISSUE THREAD

**Issue by barseghyanartur** [scrapy/scurl#60]
```
In [2]: from scurl import urlparse                                                                                                                    
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-a0b8582bdd7c> in <module>
----> 1 from scurl import urlparse

~/.virtualenvs/myenv/lib/python3.6/site-packages/scurl/__init__.py in <module>
     13 _original_urlparse = urlparse
     14 
---> 15 from scurl.cgurl import urlsplit, urljoin, urlparse
     16 """
     17 TODO: find some way to not import parse_url

ImportError: /home/user/.virtualenvs/myenv/lib/python3.6/site-packages/scurl/cgurl.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE
```

System: Ubuntu 16.04
Python 3.6

**Comment by ronen-entropius** [comment]
I have the same issue. 
Here's the Docker setup for reproduction:
```
FROM python:2.7-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    python-dev \
    libffi-dev \
    git \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app
COPY . .
RUN pip install --upgrade pip setuptools cython

RUN python setup.py build_ext --inplace
RUN python setup.py install
RUN python -c "import scurl"
```


and the build result:
```
docker build -t docker-scurl .
[+] Building 0.8s (12/12) FINISHED                                                                                                                         docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                                       0.0s
 => => transferring dockerfile: 496B                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/library/python:2.7-slim                                                                                                         0.6s
 => [internal] load .dockerignore                                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                                            0.0s
 => [1/8] FROM docker.io/library/python:2.7-slim@sha256:6c1ffdff499e29ea663e6e67c9b6b9a3b401d554d2c9f061f9a45344e3992363                                                   0.0s
 => => resolve docker.io/library/python:2.7-slim@sha256:6c1ffdff499e29ea663e6e67c9b6b9a3b401d554d2c9f061f9a45344e3992363                                                   0.0s
 => [internal] load build context                                                                                                                                          0.0s
 => => transferring context: 199.70kB                                                                                                                                      0.0s
 => CACHED [2/8] RUN apt-get update && apt-get install -y     build-essential     python-dev     libffi-dev     git     && rm -rf /var/lib/apt/lists/*                     0.0s
 => CACHED [3/8] WORKDIR /app                                                                                                                                              0.0s
 => CACHED [4/8] COPY . .                                                                                                                                                  0.0s
 => CACHED [5/8] RUN pip install --upgrade pip setuptools cython                                                                                                           0.0s
 => CACHED [6/8] RUN python setup.py build_ext --inplace                                                                                                                   0.0s
 => CACHED [7/8] RUN python setup.py install                                                                                                                               0.0s
 => ERROR [8/8] RUN python -c "import scurl"                                                                                                                               0.1s
------                                                                                                                                                                          
 > [8/8] RUN python -c "import scurl":                                                                                                                                          
0.076 Traceback (most recent call last):                                                                                                                                        
0.076   File "<string>", line 1, in <module>                                                                                                                                    
0.076   File "scurl/__init__.py", line 15, in <module>                                                                                                                          
0.076     from scurl.cgurl import urlsplit, urljoin, urlparse
0.076 ImportError: scurl/cgurl.so: undefined symbol: _ZNK4base6subtle24RefCountedThreadSafeBase6AddRefEv
------
Dockerfile:21
--------------------
  19 |     RUN python setup.py build_ext --inplace
  20 |     RUN python setup.py install
  21 | >>> RUN python -c "import scurl"
--------------------
ERROR: failed to solve: process "/bin/sh -c python -c \"import scurl\"" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/75ziclpbjrwwjus5mzy1jeqaj
```
